<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls.Core" Version="10.0.100" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <Compile Include="../../Controls/*.cs" Link="Controls/%(Filename)%(Extension)" />
    <Using Include="Microsoft.Maui.Controls" />
    <Using Include="Microsoft.Maui" />
    <Using Include="Microsoft.Maui.Graphics" />
  </ItemGroup>
</Project>
